spring.application.name=booking-service
# ------------------ SERVER CONFIG ------------------
server.port=8081

# ------------------ DATABASE CONFIG ------------------
# JDBC URL for connecting to MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/deodardreams
# Database username
spring.datasource.username=${DB_USERNAME}
# Database password
spring.datasource.password=${DB_PASSWORD}
# MySQL JDBC driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------ JPA / HIBERNATE ------------------
# Automatically update DB schema based on JPA entities (dev-friendly)
spring.jpa.hibernate.ddl-auto=update
# Print the actual SQL Hibernate generates, in the console — useful for learning/debugging
spring.jpa.show-sql=true
# Format that printed SQL so it's readable instead of one long line
spring.jpa.properties.hibernate.format_sql=true
# Log generated SQL queries (useful for debugging, disable in prod)
#spring.jpa.show-sql=false
# Enables detailed Hibernate performance statistics (disabled by default)
#spring.jpa.properties.hibernate.generate_statistics=false
# Log Hibernate internal statistics (disabled to avoid noise)
#logging.level.org.hibernate.stat=off

# ------------------ GMail Service ------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ------------------ DEODAR DREAMS CONTACT ------------------
deodar.dreams.contact-phone=${DEODAR_DREAMS_CONTACT_PHONE}
deodar.dreams.alert-mail=${DEODAR_DREAMS_CONTACT_MAIL}

# ------------------ ACTUATOR ------------------
management.endpoints.web.exposure.include=health,info,metrics

# ------------------ LOGGING ------------------
# Root application logging level
logging.level.root=INFO
# Application package logging
logging.level.com.deodardreams=INFO
# Reduce framework noise
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

management.observations.annotations.enabled=true