package com.deodardreams.model;
/**
 * Common audit fields shared by every entity in this application.
 *
 * Any entity extending this class automatically gets:
 *  - id          : primary key, auto-generated by the database
 *  - createdAt   : timestamp set automatically when the row is first saved
 *  - updatedAt   : timestamp set automatically every time the row is updated
 *  - createdBy   : admin_users.id of whoever created this row
 *  - updatedBy   : admin_users.id of whoever last modified this row
 *
 * This is a @MappedSuperclass, not a real table — Hibernate copies these
 * fields directly onto each entity's own table (e.g. physical_units gets
 * its own id/created_at/... columns). There is no separate "base_entity" table.
 *
 * createdAt/updatedAt are set automatically via @PrePersist/@PreUpdate below.
 * createdBy/updatedBy are NOT automatic — they must be set explicitly by the
 * service layer, since JPA has no way of knowing which admin user is currently
 * logged in. This can be automated later using Spring Data's @CreatedBy/
 * @LastModifiedBy auditing once Spring Security is added to the project.
 */

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Comment;

import java.time.LocalDateTime;

@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    private Long createdBy;

    private Long updatedBy;


    //This is what lets you stop manually setting createdAt/updatedAt every time you save something — Hibernate calls these for you, silently, at exactly the right moment.
    //@PrePersist means run this method automatically, right before Hibernate inserts a new row.
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    //@PreUpdate means run this automatically, right before Hibernate updates an existing row.
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
